#!/usr/bin/perl
# aStor2 -- storage area network configurable via Web-interface
# Copyright (C) 2009-2012 ETegro Technologies, PLC
#                         Sergey Matveev <sergey.matveev@etegro.com>
#                         Denis Zheleztsov <dz@etegro.com>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
use lib::IPMI;

my $STEP_TIME = 30;
my $STEP_COUNT = 60;
my $IPMITOOL = "/usr/sbin/ipmitool";

my $SENSORS_CONFIG = "/usr/lib/lua/luci/controller/san_monitoring_configuration.lua";
my $DB_PATH = "/tmp/lib/luci-bwc-ipmi";

my $BIN_TEMPLATE = "Nnnnnn";
my @SENSORS;
my %DATA;

exit 0 unless defined $ARGV[0];
lib::IPMI->config_read();
lib::IPMI->daemonize() and lib::IPMI->cycling() if $ARGV[0] eq "-d";
lib::IPMI->data_show() @ARGV;
