#!/bin/sh
# Copyright (C) 2012 Sergey Matveev (stargrave@stargrave.org)

do_mount_varlog() {
	if [ -e /dev/sda4 ]; then
		for mod in exportfs xfs; do insmod $mod; done
		mkdir -p /var/log
		if ! mount -t xfs -o sync /dev/sda4 /var/log; then
			mkfs.xfs -f /dev/sda4
		fi
	fi
}

boot_hook_add preinit_main do_mount_varlog

