#!/bin/sh

multipath_process()
{
	sleep 5
	ps | grep -q "multipath " || multipath -v0
}

case "$ACTION" in               
add)
	multipath_process
	;;
remove)
	multipath_process
	;;
esac              
