#!/bin/sh /etc/rc.common
# Copyright (C) 2009-2012 ETegro Technologies, PLC
#                         Vladimir Petukhov (vladimir.petukhov@etegro.com)

START=39
STOP=90

start()
{
if [ -r /etc/config/network ]; then
	local bonding_list=$(uci show network | grep '^network.*.type=bonding$')
	if [ "$bonding_list" != "" ]; then
		for i in $bonding_list; do
			local bondname=$(echo "$i" | sed 's/^network.\(bond[0-9]*\).type=bonding$/\1/')
			if [ "$bonding_list" != "" ]; then
				uci set network."$bondname".bondname="$bondname"
			fi
		done
		uci commit network
	fi
fi
}

stop()
{
	true
}
