#!/bin/sh

detached_hotspares()
{
		prevdir=`pwd`
		cd /sys/block
		for md in md*; do
			sleep 5
			ps | grep "mdadm /dev/$md" ||
			mdadm /dev/$md --fail detached --remove detached
		done
		cd $prevdir
}

case "$ACTION" in
add)
	detached_hotspares
	;;
remove)
	detached_hotspares
	;;
esac
