#!/bin/sh /etc/rc.common
START=50

EINARC_STARTED_FLAG="/tmp/einarc-started"

start()
{
	( # We have to daemonize this process to prevent deadlocks
	while [ ! -e $EINARC_STARTED_FLAG ]; do sleep 1; done
	echo 'lvm = require "astor2.lvm";
	      lvm.PhysicalVolume.rescan();
	      lvm.VolumeGroup.rescan();
	      lvm.LogicalVolume.rescan()' | lua -
	)&
}

stop()
{
	true
}

restart()
{
	stop
	start
}
